# Generated by Django 3.2.5 on 2021-09-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['date']},
        ),
    ]
